### ISSUE TITLE
Document how to send pull request to meta-ecm

### ISSUE THREAD

**Issue by openedev** [edgeble/contribute#1]

**Comment by moonlinux** [comment]
**Contribute to meta-ecm project**

- User need to create new pair of ssh keys and upload them to the github setting

Please follow the guidance https://docs.github.com/en/authentication/connecting-to-github-with-ssh/about-ssh

- Github requires new utility to perform this activity 

`  $ sudo apt  install gh  `

For github user, it needs to authenticate the user, select the github account, 
it will ask you to login to github using the local web browser. 
once completed it will ask enter generated passphrase from the below command
```
 $ gh auth login
? What account do you want to log into?  [Use arrows to move, type to filter]
> GitHub.com
  GitHub Enterprise Server
```
check the status of the authentication completed
```
$ gh auth status
github.com
  ✓ Logged in to github.com as moonlinux (/home/amoon/.config/gh/hosts.yml)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: *******************
```

- Clone and push the changes to github repository 
do local changes in the repository and verify the changes, so that they can be reviewed.

```
$ git clone git@github.com:edgeble/meta-ecm.git
$ git add         # modified the files
$ git commit   # add a suitable commit message to describe the changes
```

Verify the build and feature work correctly as per the requirement.

- Git push the changes for review via new gh command 
Add the new remote github username to the existing local branch 

```
$ git remote add username git@github.com:username/meta-ecm.git
verify the user name is added t
$ git remote -v
username     git@github.com:username/meta-ecm.git (fetch)
username      git@github.com:username/meta-ecm.git (push)
origin  git@github.com:edgeble/meta-ecm.git (fetch)
origin  git@github.com:edgeble/meta-ecm.git (push)
```

- Push the change to github repository 

`$ git push username kirkstone:kirkstone -f`

- Send a pull request to the original repository 

`$ gh pr create --title "Suitable title" --body "describes the commit changes"`

**Comment by openedev** [comment]
Thanks. Please update this on README.md and send PR.
